package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
//mybatis-plus mapper scan
//@MapperScan("example.hello_security.mapper")
//springboot组件扫描，当多模块时如果项目启动类的文件路径和其他模块的路径不一致是需要使用ComponentScan；否则会扫描不到
//不使用@Componentscan了，直接改文件名
//@ComponentScan(basePackages ={"com.example.quartz.*","example.hello_security.*"})
public class HelloSecurityApplication {

	// 生成密码：446752f2-202b-4ad6-a48e-e3d9f008b5e3
	public static void main(String[] args) {
		SpringApplication.run(HelloSecurityApplication.class, args);
	}

}
