package example.hello_security;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
//@MapperScan("example.hello_security.mapper")
public class HelloSecurityApplication {

	// 生成密码：446752f2-202b-4ad6-a48e-e3d9f008b5e3
	public static void main(String[] args) {
		SpringApplication.run(HelloSecurityApplication.class, args);
	}

}
